In [1]:
import numpy as np

In [207]:
a = np.array([1,2,3], dtype ='int16')
print(a)

[1 2 3]


In [198]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
a.ndim

1

In [6]:
b.shape

(2, 3)

In [206]:
a.dtype

dtype('int32')

In [208]:
a.itemsize

2

In [202]:
a.size

3

In [20]:
a.size*a.itemsize

6

In [21]:
a.nbytes

6

In [ ]:
#Changing Element Rows, Columns etc

In [211]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
a[1,-2]

13

In [24]:
a[1,5]

13

In [30]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
a[:,0]

array([1, 8])

In [31]:
a[0,1:6:2]

array([2, 4, 6])

In [34]:
a[0,1:-2:2]

array([2, 4])

In [213]:
a[0,1:-1:2]

array([2, 4, 6])

In [44]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [45]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [46]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [48]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
b[0,1,1]

4

In [51]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [53]:
#Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [55]:
#All zeroes matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.zeros([2,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [60]:
np.zeros([2,3,3,2])

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [64]:
np.ones([4,2,2], dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [68]:
np.full([2,2],99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [70]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [71]:
#OR
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [72]:
np.random.rand(4,2)

array([[0.66741056, 0.67128044],
       [0.32951648, 0.16780122],
       [0.47680412, 0.98286807],
       [0.85082679, 0.3765499 ]])

In [220]:
np.random.rand(4,2,3)

array([[[0.87084387, 0.92619318, 0.03623587],
        [0.02529587, 0.14701609, 0.43798878]],

       [[0.19260594, 0.49311899, 0.10012405],
        [0.45258759, 0.58836236, 0.71131376]],

       [[0.84715311, 0.73409752, 0.8953199 ],
        [0.22727698, 0.37980971, 0.20303848]],

       [[0.20889409, 0.71683384, 0.84505312],
        [0.82441419, 0.90340689, 0.92186055]]])

In [76]:
np.random.random_sample(a.shape)

array([[0.52348146, 0.57986885, 0.85754166, 0.4645098 , 0.85487196,
        0.2278449 , 0.71130991],
       [0.1064254 , 0.14086782, 0.60477871, 0.24027929, 0.17069495,
        0.94688521, 0.34043181]])

In [98]:
#random int
np.random.randint(2,7, size=(3,3))

array([[6, 4, 2],
       [2, 2, 2],
       [3, 5, 6]])

In [99]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [114]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [117]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [121]:
output = np.ones([5,5])
print(output)

z = np.zeros([3,3])
z[1,1] = 9
print(z)

output[1:4,1:4] = z #or output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [123]:
#Copy function to maintain values of a
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


In [ ]:
#Mathematics

In [125]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [126]:
a+2

array([3, 4, 5, 6])

In [127]:
a-2

array([-1,  0,  1,  2])

In [128]:
a*2

array([2, 4, 6, 8])

In [129]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [130]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [131]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [132]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
#Linear Algebra

In [136]:
a = np.ones([2,3])
print(a)

b = np.full([3,2],2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [141]:
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [142]:
np.linalg.det(c)

1.0

In [ ]:
#Statistics

In [144]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
np.min(stats)

1

In [149]:
np.min(stats, axis = 1)

array([1, 4])

In [146]:
np.max(stats)

6

In [150]:
np.sum(stats)

21

In [153]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [ ]:
#reorganising arrays

In [156]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [158]:
after = before.reshape([8,1])
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
#Vertically Stacking Vectors

In [160]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#Horizontally Stacking Vectors

In [161]:
h1 = np.ones([2,4])
h2 = np.zeros([2,2])

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
#Miscellaneous

In [176]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [168]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [169]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [175]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [178]:
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [180]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [182]:
(~((filedata>50)&(filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [171]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
#Quiz

In [188]:
a = np.random.randint(2,7, size=(6,5))
print(a)

[[3 5 6 6 5]
 [4 2 5 6 4]
 [3 2 4 6 5]
 [3 6 4 4 4]
 [2 5 3 5 4]
 [2 3 6 5 2]]


In [189]:
a[2:4,0:2]

array([[3, 2],
       [3, 6]])

In [190]:
a[[0,1,2,3],[1,2,3,4]]

array([5, 5, 6, 4])

In [191]:
a[[0,4,5],3:]

array([[6, 5],
       [5, 4],
       [5, 2]])